FIX return object for getters
Issue: Got following exception when call the Map.getMaxZoom()

java.lang.ClassCastException: java.lang.String cannot be cast to
java.lang.Number
	at net.java.html.leaflet.Map.getMaxZoomInternal(Map.java)
	at net.java.html.leaflet.Map.getMaxZoom(Map.java:539)

Root cause:
 Missed the keyword return in the JavaScript Body

Fix:
Add the return keyword